google:
  recaptcha:
    v3:
      api:
        secret-key: ${RECAPTCHA_SECRET_KEY}
        host: https://www.google.com
        site-key: ${RECAPTCHA_SITE_KEY}
        url: /recaptcha/api/siteverify
web:
  location:
    signup: http://localhost:9080
    index: http://localhost:8000
    logout: http://localhost:8090/logout
    signin: http://localhost:8090
feign:
  client:
    config:
      default:
        logger-level: FULL
        read-timeout: '10000'
        connect-timeout: '5000'
cookie:
  token:
    name: Authorization
  auth-failure:
    name: AUTHORIZATION_FAILURE
spring:
  security:
    ignore-matchers: /,/signin,/signin/**,/logout
  thymeleaf:
    cache: 'false'
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: 'true'
auth:
  server:
    be:
      unionapi:
        base: http://localhost:10000
        login:
          nonsocial:
            url: /api/v1/auth/login/nonsocial
          kakao:
            url: /api/v1/auth/login/social/kakao
        client-info:
          url: /api/v1/auth/client-info
logging:
  level:
    io:
      github:
        rojae:
          authsigninweb: debug
server:
  port: '8090'
